<?php /**
 * zeonsolutions inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.zeonsolutions.com/shop/license-enterprise.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * This package designed for Magento ENTERPRISE edition
 * =================================================================
 * zeonsolutions does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * zeonsolutions does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   design
 * @package    base_default
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2013 zeonsolutions.Inc. (http://www.zeonsolutions.com)
 * @license    http://www.zeonsolutions.com/shop/license-enterprise.txt
 */ ?>
<?php $_manufacturersCollection = $this->getManufacturersCollection(); ?>
<div class="brands">
    <h2 class="brands-title">
        <?php echo $this->__('Brands you know & love') ?>
    </h2>
    <div class="brands-content">
            <?php $_iterator = 0; ?>
            <ul class="brand-slider">
                <?php foreach ($_manufacturersCollection as $_manufacturer): ?>
                    <li class="item">
                        <a href="<?php echo $this->getUrl('manufacturers' . '/' . $_manufacturer->getIdentifier()) ?>" title="<?php echo $_manufacturer->getManufacturer() ?>"><img alt="<?php echo $_manufacturer->getManufacturerLogo() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'manufacturer' . '/' . $_manufacturer->getManufacturerLogo() ?>" width="180"></a>                       
                    </li>
                <?php endforeach; ?>
            </ul>
            <div class="all-brands">
                <a href="<?php echo $this->getUrl('manufacturers') ?>" title="<?php echo $this->__('View All123') ?>"><?php echo $this->__('View All Brands') ?></a>
            </div> 
    </div>
</div>
<script type="text/javascript">
        
          jQuery(document).ready(function() {
            jQuery(".brand-slider").slick({
                slidesToShow: 4,
                slidesToScroll: 2,
                autoplay: true,
                arrows:false,
                responsive: [
                    {
                      breakpoint: 1170,
                      settings: {
                        slidesToShow: 4
                      }
                    },
                    {
                      breakpoint: 768,
                      settings: {
                        slidesToShow: 3
                      }
                    },
                    {
                      breakpoint: 480,
                      settings: {
                        slidesToShow: 2
                      }
                    }
                ]
            }); 
          });
        
    </script>