<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php $_logo = Mage::getStoreConfig('tab1/main_options/logo'); ?>
<?php $_retina_logo = Mage::getStoreConfig('tab1/main_options/retina_logo'); ?>

<div class="loading-anim"></div>
<div class="loader-overlay">
    <div class="loader"></div>
</div>

<div class="header">
<div class="container">
    <header role="banner">
        <div class="row">
            <div class="header-custom-block col-md-5">
                <?php echo $this->getChildHtml('phone_number'); ?>
                <?php echo $this->getChildHtml('header_notice'); ?>
            </div>
            <div class="logo-container col-md-2">
                
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $_logo; ?>" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $_logo; ?>" alt="<?php echo $this->getLogoAlt() ?>" data-src-retina="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $_retina_logo; ?>" class="lazy-load" width="180" /></a>
                
            </div>
            <div class="col-md-5">
                <div class="quick-access">
                    <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
                        <?php echo $this->getChildHtml('topLinks') ?>
                        <?php //echo $this->getChildHtml('store_language') ?>
                    <?php //echo $this->getChildHtml('topSearch') ?>
                    
                </div>
            </div>
            <?php echo $this->getChildHtml('topContainer'); ?>
        </div>
    </header>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
</div>

<script type="text/javascript">
    jQuery(function() {
        var header = jQuery('.main-nav').offset().top;
        jQuery(window).scroll(function(){
            if( jQuery(window).scrollTop() > header ) {
                jQuery('.main-nav').addClass("fixed-header");
            }else{
                jQuery('.main-nav').removeClass("fixed-header");
            }
        });

       
    });
</script>


