<?php if($this->getMessagesBlock()->getMessageCollection()->count()): ?>
	<div id="camel_global_messages" style="display: none">
		<a href="javascript:void(0)" id="camel_global_messages_close" style="display: none" title="<?php echo $this->__('Hide messages') ?>">&times;</a>
		<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
	</div>
<?php $this->getMessagesBlock()->getMessageCollection()->clear(); ?>
 
<script type="text/javascript">
//<![CDATA[
	Event.observe('camel_global_messages_close', 'click', function() {
		Effect.SlideUp('camel_global_messages', { duration: 0.4, delay: 0.3 });
		Effect.Fade('camel_global_messages_close', { duration: 0.2 });
	});
	Event.observe(document, 'dom:loaded', function() {
		Effect.SlideDown('camel_global_messages', { duration: 0.4, delay: 0.3 });
		Effect.Appear('camel_global_messages_close', { duration: 0.2, delay: 1 });
	});
//]]>
</script>
 
<?php endif; ?>