<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
echo $this->getDesignStyles();
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
$is_persistent = Mage::helper('opc')->isPersistentMember();
?>
<div class="opc-wrapper-opc design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
    <h2><?php echo $this->__('Checkout')?></h2>

    <p class="opc-desc"><?php echo $this->__('Complete your order in a single step by entering your details below.'); ?></p>
	<div class="opc-menu">
<?php if(!$is_persistent):?>	
	    <?php echo $this->getChildHtml('paypal.button')?>

        <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
    		<?php echo $this->getChildHtml('login');?>	
    	<?php endif;?>    	
    	
    	
	   <div class="clear move-columns"></div>
<?php else:?>
	<?php echo $this->getChildHtml('login');?>
<?php endif;?>
	</div>
	
	<div class="clear"></div>

<div <?php if($is_persistent):?>style="display:none !important;"<?php endif;?>>

    <div class="opc-col-left">
		<form id="opc-address-form-billing" method="post">
        	<?php echo $this->getChildHtml('billing')?>
        </form>
        <?php echo $this->getChildHtml('opc.newsletters');?>

        <form id="opc-address-form-shipping" class="hidden" method="post">
        <?php echo $this->getChildHtml('shipping')?>
        </form>
		
    </div>

    <div class="opc-col-center">
       <?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
    	<div class="shipping-block">
        	<h3><?php echo $this->__('Shipping Method')?></h3>
        	<div id="shipping-block-methods">
				<?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
			</div>
		</div>
		<?php endif;?>

		<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
			<h3><?php echo $this->__('Payment Method')?></h3>
			<?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
		</div>

		<?php if(Mage::helper('opc')->isShowComment()):?>
				<?php echo $this->getChildhtml('customer.comment');?>
			<?php endif;?>
		
		<?php if(Mage::helper('opc')->isShowDiscount()):?>
		<!-- div class="discount-block">
			<h3><?php echo $this->__('Discount Codes')?><span class='fa expand_plus'></span></h3>
			<div  class="collapse-block hidden">
			     <?php echo $this->getChildhtml('coupon');?>
			</div>
		</div -->
		<?php endif;?>

		
    </div>

    <div class="opc-col-right">
		
		<div class="review-block">
			<h3><?php echo $this->__('Review Your Order')?></h3>
			<div valign="middle">
                <?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a>
            </div>
    	  	<div id="opc-review-block">
		      	<?php echo $this->_getReviewHtml()?>
		  	</div>
		</div>
    
        <?php if (Mage::getConfig()->getModuleConfig('IWD_OnepageCheckoutSignature')->is('active', 'true')): ?>
            <div class="signature-block">
                <h3><?php echo $this->__('Signature')?><span class='fa expand_plus'></span></h3>
                <div  class="collapse-block hidden">
                    <?php echo $this->getChildhtml('opcsignature');?>
                </div>
            </div>
        <?php endif;?>

		<div class="opc-review-actions" id="checkout-review-submit">
		      
		      <?php echo $this->getChildHtml('agreements')?>

		      

		      <button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><span><span><?php echo $this->__('Place Order Now') ?></span></span></button>
		</div>
    </div>
    
</div>

</div>
<script>
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("IWD_Opc")->version;?>';
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>
</script>

<div id="agree_error" style="display:none !important;"><?php echo $this->__('Please agree to all the terms and conditions before placing the order.');?></div>
<div id="pssm_msg" style="display:none !important;"><?php echo $this->__('Please specify shipping method.');?></div>
<div class="opc-ajax-loader">
	<div id="floatingCirclesG">
		<div class="f_circleG" id="frotateG_01"></div>
		<div class="f_circleG" id="frotateG_02"></div>
		<div class="f_circleG" id="frotateG_03"></div>
		<div class="f_circleG" id="frotateG_04"></div>
		<div class="f_circleG" id="frotateG_05"></div>
		<div class="f_circleG" id="frotateG_06"></div>
		<div class="f_circleG" id="frotateG_07"></div>
		<div class="f_circleG" id="frotateG_08"></div>
	</div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	
	<div class="opc-messages">
		<a class="close-message-wrapper"><i class="fa fa-close"></i></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>